### ISSUE TITLE
A filename can't contain following characters in Windows

### ISSUE THREAD

**Issue by Z9RO** [yihong0618/Kindle_download_helper#10]
'\/:*?"<>|' 这些无法作为 Windows 的文件名，会导致在 Windows 上无法保存文件，比如这个 [带了英文冒号](https://www.amazon.cn/dp/B00GQUBLK6)
`filename = re.sub(r'[\\/:*?"<>|]', '_',  filename)` 类似的正则应该能解决

**Comment by yihong0618** [comment]
嗯是的，请问有兴趣提个 PR 么？

**Comment by Z9RO** [comment]
很乐意，不过里面大部分在 Unix 下是合法的，需要区分操作系统处理吗

**Comment by yihong0618** [comment]
我觉得不区分暂时也没问题
如果区分的话 os.system 判断应该就可以
