### ISSUE TITLE
Setting for Amazon UK?

### ISSUE THREAD

**Issue by doglove9394** [yihong0618/Kindle_download_helper#104]
Hi there, is there any one know the setting for Amazon UK?

Thanks a lot in advance.

**Comment by yihong0618** [comment]
supported now(maybe)
please use latest code then follow the `README` with arg `--uk`

**Comment by yihong0618** [comment]
@doglove9394 closing it now, if you still problem we will reopen it.

**Comment by doglove9394** [comment]
Thanks a lot, sorry my mail put in spam and just learn that this update. Thank you very much.
