### ISSUE TITLE
无法下载pdoc

### ISSUE THREAD

**Issue by bk1412** [yihong0618/Kindle_download_helper#108]
下面是控制台日志，电脑和服务器都试了，服务器是arm64 ubuntu，而且服务器上自动获取cookie不好使...

ubuntu@instance:~/Kindle_download_helper-main$ python3 kindle.py --cookie-file ./1 --pdoc
<re.Match object; span=(104877, 104988), match='var csrfToken = "g1PpelHcEEPzfD9xZOXNEarMva7d24Uq>
Amazon bot check detected, sleep 3 sec
Using default device serial Number: 3AF4596C58AE4083895190D1695B4AF8
It will take some time to get all PDOC books list, please wait
'customerId'

'customerId'
Title: 哆啦A夢 - 卷04, Asin: H44GKRNS5PYZB5PPWWFV2CAMHSP4IXRM download failed
'customerId'
Title: 哆啦A夢 - 卷05, Asin: PO6MA4WVDLQ6B4LZ3C7OBCVK46OE36XD download failed
'customerId'
Title: 哆啦A夢 - 卷01, Asin: 2G4XFFACJA4IX2B53R5CSZTRRSMKQOBB download failed
'customerId'
Title: 哆啦A夢 - 卷02, Asin: VV2QCFMW4M5TT6EGRQ5O7DRLLFFQCDHS download failed
'customerId'
Title: 哆啦A夢 - 卷03, Asin: A53UELQEMCDFZFO3ZTIGE4SBRRUJN6VL download failed

All done!
Now you can use apprenticeharper's DeDRM tools (https://github.com/apprenticeharper/DeDRM_tools)
with the following serial number to remove DRM: xxxxxxxxxxxxxxxxxxx(隐藏)
the device serial number can also be found here: DOWNLOADS/key.txt
ubuntu@instance:~/Kindle_download_helper-main$

**Comment by yihong0618** [comment]
我晚上看看

**Comment by yihong0618** [comment]
@bk1412 是都下不了还是这几本下不了？

**Comment by bk1412** [comment]
> @bk1412 是都下不了还是这几本下不了？

我pdoc所有的都下不了，一点都是download fail,异常我打印出来了，'customerId'就是异常

**Comment by yihong0618** [comment]
我正在测验没问题，请试试 cli?

**Comment by bk1412** [comment]
刚试了，还是不行，pdoc的文件有什么日期限制吗？
![1677318394934338023450586301126](https://user-images.githubusercontent.com/55432442/221350501-43ffaa60-c15a-4d8e-95f6-497326625ec8.jpg)

**Comment by yihong0618** [comment]
我想想，你有实体的 kindle 设备么？

**Comment by bk1412** [comment]
> 我想想，你有实体的 kindle 设备么？

没有，这些漫画是之前推送到iPad上面的kindle来看的

**Comment by yihong0618** [comment]
那可能不行，参考其它 issue 没有设备怎么办

**Comment by bk1412** [comment]
> 那可能不行，参考其它 issue 没有设备怎么办

没看到相关的issue，能发个链接吗

**Comment by bk1412** [comment]
> 那可能不行，参考其它 issue 没有设备怎么办

我看到了相关的issue，关于下载旧版app之类的操作，我想问是这么操作完以后就一劳永逸了吗，还是次次都要通过那个程序进行转格式之类的操作。

**Comment by yihong0618** [comment]
应该一次就可以。

**Comment by bk1412** [comment]
> 应该一次就可以。

还是不行，已经用旧版登录，并且设置为默认设备了，估计没实体机做不到下载pdoc了
