### ISSUE TITLE
貌似没有办法下载美亚的书

### ISSUE THREAD

**Issue by chwdy** [yihong0618/Kindle_download_helper#114]
运行 `python kindle.py` 会自动打开自己的内容的那个页面，但同时会报错退出

> Traceback (most recent call last):
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle.py", line 5, in <module>
>     main()
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/cli.py", line 317, in main
>     kindle.download_books(
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 529, in download_books
>     device = self.find_device()
>              ^^^^^^^^^^^^^^^^^^
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 130, in find_device
>     devices = self.get_devices()
>               ^^^^^^^^^^^^^^^^^^
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 214, in get_devices
>     self.ensure_cookie_token()
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 187, in ensure_cookie_token
>     self._csrf_token = self._get_csrf_token()
>                        ^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 157, in _get_csrf_token
>     raise Exception(
> Exception: Can't get the csrf token, please refresh the page at https://www.amazon.com/hz/mycd/myx#/home/content/booksAll and retry

如果手动指定crsf 和cookie ，会一直有

> Traceback (most recent call last):
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle.py", line 5, in <module>
>     main()
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/cli.py", line 317, in main
>     kindle.download_books(
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 529, in download_books
>     device = self.find_device()
>              ^^^^^^^^^^^^^^^^^^
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 130, in find_device
>     devices = self.get_devices()
>               ^^^^^^^^^^^^^^^^^^
>   File "/Users/Diwei/Documents/Kindle_download_helper/kindle_download_helper/kindle.py", line 228, in get_devices
>     raise Exception(
> Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie

尝试过手动设定相同的参数在postman ，得到相同的结果，不知道是不是漏了什么参数，还是说美亚的网站设置不一样
<img width="977" alt="image" src="https://user-images.githubusercontent.com/15193485/227669804-2b7a45f2-d49a-4a0f-ba6f-bc9b559f0faf.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/15193485/227669814-8536e4db-7cab-4024-b03b-774d34245118.png">

---

另外在这个位置，没有参数的时候是不是默认应该是“com“而不是”cn“？

https://github.com/yihong0618/Kindle_download_helper/blob/9890671bdcd12324653353c91b5b5c47dc01711a/kindle_download_helper/kindle.py#LL58C8-L58C8

**Comment by yihong0618** [comment]
是，没有参数默认是 com.
但是下载美亚（中亚）也是，现在阶段必须要有实体设备，用 app 不行，之后可能会更新，不用设备也行

**Comment by chwdy** [comment]
实体设备是指必须账户里面有一台kindle paperwhite或者fire之类的设备么？

**Comment by yihong0618** [comment]
是的，fire 应该不行，得是 e-link fire 的本质是安卓 app

**Comment by YuanH** [comment]
我也有同样的问题：
`python3 kindle.py --cookie-file ./cookie_file.txt g7Vx3IS1mZaqzW0esp8oUX8m7LC0TgoRSrXxEfj3IfWeAAAAAQAAAABkIl5kcmF3AAAAAFgvVn10EP4nuL9RKfa6ow==
Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "/Users/yuan/Documents/kindle/Kindle_download_helper/kindle.py", line 5, in <module>
    main()
  File "/Users/yuan/Documents/kindle/Kindle_download_helper/kindle_download_helper/cli.py", line 317, in main
    kindle.download_books(
  File "/Users/yuan/Documents/kindle/Kindle_download_helper/kindle_download_helper/kindle.py", line 529, in download_books
    device = self.find_device()
  File "/Users/yuan/Documents/kindle/Kindle_download_helper/kindle_download_helper/kindle.py", line 130, in find_device
    devices = self.get_devices()
  File "/Users/yuan/Documents/kindle/Kindle_download_helper/kindle_download_helper/kindle.py", line 228, in get_devices
    raise Exception(
Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie`

**Comment by yihong0618** [comment]
现在必须要有实体设备了。。。

**Comment by YuanH** [comment]
我有实体设备啊

**Comment by YuanH** [comment]
不好意思才看到。是的绑定了。
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1266145/229598480-4e0d2f8b-b473-4df8-b451-cc6f17059071.png">

**Comment by yihong0618** [comment]
可以尝试置顶的方法试试。
