### ISSUE TITLE
warning: bad key, size, value combination detected in EXTH 406...

### ISSUE THREAD

**Issue by chinsansan** [yihong0618/Kindle_download_helper#121]
按照 cli 操作，用自动获取 ```python3 kindle.py  --dedrm --cn```
可以获取并下载 amazon cn 账号里的kindle书籍，但是每本书下载的时候都会显示 
```warning: bad key, size, value combination detected in EXTH 406 16 0000000000000```
下载到本地的书籍也都能打开看，不确定这个提示会有什么问题。

大概查了一下，似乎是 kindleunpack 里的一个提示：
[mobileread 1](https://www.mobileread.com/forums/showthread.php?t=247087&page=8)
[mobileread 2](http://www.mobileread.mobi/forums/showthread.php?t=61986&page=102)

**Comment by yihong0618** [comment]
你可能需要在网页端改下默认的 kindle 变成实体设备

**Comment by zteshadow** [comment]
我也遇到同样的问题, 去掉`--dedrm`就可以下载了. 下载完会提示如何dedrm, 感谢楼主, 也希望对你有帮助

**Comment by yihong0618** [comment]
哈？理论上不会呀，我看看哈

**Comment by chinsansan** [comment]
我下载的时候虽然有 warning提示，但也可以正常下载书籍，下载到本地也能阅读，没有提示DRM。

**Comment by xavierskip** [comment]
我也有相应的提示，目前没发现哪里出了问题。

**Comment by yihong0618** [comment]
目前看可以忽略
