### ISSUE TITLE
日亚无法获取书籍列表 

### ISSUE THREAD

**Issue by kmlixh** [yihong0618/Kindle_download_helper#126]
1.4.1日亚无法获取文件列表

**Comment by yihong0618** [comment]
有什么报错么

**Comment by kmlixh** [comment]
检查发现是cookie无效，但是更新cookie后仍然无法下载

**Comment by kmlixh** [comment]
经过测试发现，使用document.cookie获取到的token是无效的
，无法获取图书列表，也拿不到crsfToken

**Comment by yihong0618** [comment]
用第一种方式试试？
python no_kindle.py -e ${email} -p ${password} --jp
