### ISSUE TITLE
cookie 是指整个 cookies 吗

### ISSUE THREAD

**Issue by littledu** [yihong0618/Kindle_download_helper#13]
1. 获取 cookie
控制台使用 `document.cookie` 把取到的值直接透传

2. csrf_token，直接在源代码里面找到

但总是返回权限错误，如图：
<img width="2545" alt="image" src="https://user-images.githubusercontent.com/1784673/172284808-e5b7aa4e-24c0-444e-8b42-f767b2b8be36.png">

是不是我获取 cookie 的姿势不对？

**Comment by yihong0618** [comment]
是的，可能和 #6 一致，请问是否用的 firefox?

我感觉 #9 合并了之后能方便一点，你也可以直接 Pull #9 PR 的代码尝试一下。

**Comment by littledu** [comment]
@yihong0618 是 chrome，我看一下 #6 哈，不行就试试 pull #9

**Comment by wolfg1969** [comment]
> 是的，可能和 #6 一致，请问是否用的 firefox?
> 
> 我感觉 #9 合并了之后能方便一点，你也可以直接 Pull #9 PR 的代码尝试一下。

确实，用 #9 的代码成功了

**Comment by littledu** [comment]
用新版可以了
