### ISSUE TITLE
Miss font family 下载失败

### ISSUE THREAD

**Issue by blogwy** [yihong0618/Kindle_download_helper#131]
使用python no_kindle.py -e ${email} -p ${password}下载的时候，出现warn: miss font family names Microsoftyahei,Stkaiti 导致有一本书下载失败

**Comment by yihong0618** [comment]
@blogwy 没失败，这个是 warn 因为 kfx 需要读取 font, 这个可以忽略。/

**Comment by johnzhou2011** [comment]
遇到同样的问题，提示错误后，只下载了一本书，不确定是不是错误提示后中断了下载，或者这个命令不下载“个人文档”。

**Comment by yihong0618** [comment]
不能下载个人文档的现在😂稍后会更新

**Comment by yihong0618** [comment]
@johnzhou2011 支持了个人文档
