### ISSUE TITLE
503 Server  与 404 Client 错误

### ISSUE THREAD

**Issue by GoingTime** [yihong0618/Kindle_download_helper#134]
开始下载后出现多个 503 错误，随后所有的错误都是 404。

`.error_books.log`文件内容始终为空。

![image](https://github.com/yihong0618/Kindle_download_helper/assets/24788382/54990404-6636-40aa-84e0-7516a025e014)

![image](https://github.com/yihong0618/Kindle_download_helper/assets/24788382/106bc3df-e73b-4ad2-8a12-c0592c1ea4ac)

**Comment by yihong0618** [comment]
@GoingTime 如果没有实体设备的话需要用 README 中置顶的方式。

**Comment by yihong0618** [comment]
目前来说，是的。

**Comment by yihong0618** [comment]
先关了哈

**Comment by IzualYang** [comment]
```
Authenticating . . .
{"response": {"challenge": {"challenge_reason": "HandleOnWebView", "uri": "https://www.amazon.cn/ap/challenge?arb=xxx"}}, "request_id": "xxx"}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "e:\Kindle\no_kindle.py", line 5, in <module>
    no_main()
  File "e:\Kindle\kindle_download_helper\no_cli.py", line 101, in no_main
    nk.make_library()
  File "e:\Kindle\kindle_download_helper\no_kindle.py", line 154, in make_library
    r = self.session.send(
        ^^^^^^^^^^^^^^^^^^
  File "e:\Kindle\kindle_download_helper\no_kindle.py", line 40, in new_send
    return old_send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\sessions.py", line 682, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\requests\utils.py", line 869, in resolve_proxies
    url = request.url
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by yihong0618** [comment]
@IzualYang 应该是触发风控了，在网页端重新登陆。

**Comment by yihong0618** [comment]
> ```
> Authenticating . . .
> {"response": {"challenge": {"challenge_reason": "HandleOnWebView", "uri": "https://www.amazon.cn/ap/challenge?arb=xxx"}}, "request_id": "xxx"}
> Could not retrieve auth tokens
> Traceback (most recent call last):
>   File "e:\Kindle\no_kindle.py", line 5, in <module>
>     no_main()
>   File "e:\Kindle\kindle_download_helper\no_cli.py", line 101, in no_main
>     nk.make_library()
>   File "e:\Kindle\kindle_download_helper\no_kindle.py", line 154, in make_library
>     r = self.session.send(
>         ^^^^^^^^^^^^^^^^^^
>   File "e:\Kindle\kindle_download_helper\no_kindle.py", line 40, in new_send
>     return old_send(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\requests\sessions.py", line 682, in send
>     kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Python311\Lib\site-packages\requests\utils.py", line 869, in resolve_proxies
>     url = request.url
>           ^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'url'
> ```

https://github.com/yihong0618/Kindle_download_helper/issues/129

**Comment by IzualYang** [comment]
> @IzualYang 应该是触发风控了，在网页端重新登陆。

网页端退出重登了，命令行仍然一样

**Comment by yihong0618** [comment]
> > @IzualYang 应该是触发风控了，在网页端重新登陆。
> 
> 网页端退出重登了，命令行仍然一样

是否有 2FA?
<img width="1081" alt="image" src="https://github.com/yihong0618/Kindle_download_helper/assets/15976103/5a7d5196-9ce5-4814-b3db-fffaba74ab99">
点这个然后会让你重新输入密码，再试试，如果不行那应该就是被风控了
