### ISSUE TITLE
AUTHENTICATION_ERROR 

### ISSUE THREAD

**Issue by wesley7891** [yihong0618/Kindle_download_helper#14]
![image](https://user-images.githubusercontent.com/94120374/172288161-4e5df4b1-8a99-4424-9ecf-d03043de80d4.png)

**Comment by yihong0618** [comment]
1. 浏览器访问后面的网址再跑一遍试试
2. 看看和 #6 是否一致，firefox 可能暂时不行，我下午修一下
3. 看看 #9 PR 的代码是否可以，同样下午这个 PR 我看一下然后合了
4. 都不行的话，可能是只用了 kindle 没有购买 kindle 硬件的原因

**Comment by littledu** [comment]
@yihong0618 
1. 我是 chrome
2. 使用 #9 PR 的代码，试了下还是一样（PS: #9 貌似改变了传参，按新传参试的）
3. 我确实没有买 kindle 硬件

**Comment by wesley7891** [comment]
> ![image](https://user-images.githubusercontent.com/94120374/172288161-4e5df4b1-8a99-4424-9ecf-d03043de80d4.png)

好的 中午试一试，我有一台kindle 但最近退出了账号 可能是这个原因

**Comment by yihong0618** [comment]
merge 了，大家可以再试一下
ps. 命令有些变更原来的 `--is-cn` 变成了 `--cn`

**Comment by elricli** [comment]
我这边还是一样。
情况：
- 有 Kindle 设备
- 尝试过重新刷新页面
- 使用 `--cn` 参数
- Kindle 设备登录着账号
- 使用 `Edge` 浏览器

**Comment by yihong0618** [comment]
> 我这边还是一样。 情况：
> 
> * 有 Kindle 设备
> * 尝试过重新刷新页面
> * 使用 `--cn` 参数
> * Kindle 设备登录着账号
> * 使用 `Edge` 浏览器

-  chrome 试一下？
- 试试重新拿 csrf token.

**Comment by littledu** [comment]
@yihong0618 我的成功了，提个建议，readme 最前面的环境配置，不要用 pip，因为用了 python3，貌似就不能直接使用 pip 了，我是用 pip3 安装的，但如果不知道的可能就会去搜索安装 pip 了

**Comment by littledu** [comment]
@yihong0618 书会下载在 `DOWNLOADS`  里，容易让人误触，我坑 chi 坑 chi 在 downloads 目录找就是没找到，最后原来是在执行的目录下的 `DOWNLOADS` 里

**Comment by littledu** [comment]
@yihong0618 可以的，我提一个

**Comment by talentldk** [comment]
我也有这个问题，尝试了edge和chrome，隐身模式，都是这个报错

**Comment by fengzhao** [comment]
我还是不行

**Comment by fengzhao** [comment]
- 有 Kindle 设备
- 尝试过重新刷新页面
- 使用 --cn 参数
- Kindle 设备登录着账号
使用 Edge 浏览器

**Comment by bugxch** [comment]
相同的问题，
kindle设备登录，
尝试刷新页面，
使用--cn参数
edge浏览器

**Comment by bugxch** [comment]
相同的问题，
kindle设备登录，
尝试刷新页面，
使用--cn参数
edge浏览器

**Comment by yihong0618** [comment]
大家试试 #19

**Comment by fengzhao** [comment]
> 大家试试 #19

不太懂merge和pr，是直接 git pull origin main 再试试吗？

**Comment by fengzhao** [comment]
got it , 已下载完成，谢谢你

**Comment by yihong0618** [comment]
> got it , 已下载完成，谢谢你

客气了，just enjoy~
