### ISSUE TITLE
python no_kindle.py -e ${email} -p ${password} download failure

### ISSUE THREAD

**Issue by ruby109** [yihong0618/Kindle_download_helper#149]
I was using `python no_kindle.py -e ${email} -p ${password} --jp`.

There is the error message

```
Authenticating . . .
{"response": {"error": {"code": "ThrottledRequest", "message": "The request has been throttled."}}, "request_id": "7b134bef4fc44aac9cf8f2464292f8fb"}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "/Users/l_shen/Kindle_download_helper/no_kindle.py", line 5, in <module>
    no_main()
  File "/Users/l_shen/Kindle_download_helper/kindle_download_helper/no_cli.py", line 120, in no_main
    nk.make_library()
  File "/Users/l_shen/Kindle_download_helper/kindle_download_helper/no_kindle.py", line 167, in make_library
    r = self.session.send(
        ^^^^^^^^^^^^^^^^^^
  File "/Users/l_shen/Kindle_download_helper/kindle_download_helper/no_kindle.py", line 45, in new_send
    return old_send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/l_shen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/requests/sessions.py", line 684, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/l_shen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/requests/utils.py", line 874, in resolve_proxies
    url = request.url
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by yihong0618** [comment]
only support cn now, if you are jp account try to login on web and use this script again

**Comment by ruby109** [comment]
I see.
I've tried again and it doesn't seem to work. :-(

**Comment by imwsl** [comment]
I met the same error, and I don't know how to fix it.

**Comment by yihong0618** [comment]
> I met the same error, and I don't know how to fix it.
> 
> <img alt="image" width="947" src="https://user-images.githubusercontent.com/94120374/282027555-ca053f61-0e4a-4a5e-857b-711a6425611b.png">

cn account?

**Comment by imwsl** [comment]
> > I met the same error, and I don't know how to fix it.
> > <img alt="image" width="947" src="https://user-images.githubusercontent.com/94120374/282027555-ca053f61-0e4a-4a5e-857b-711a6425611b.png">
> 
> cn account?

Yes, I found this type, the dictionary has no 'Purchase' value.

<img width="398" alt="image" src="https://github.com/yihong0618/Kindle_download_helper/assets/94120374/d07e3469-d277-4248-b756-1739bbf091f7">

**Comment by yihong0618** [comment]
> > > I met the same error, and I don't know how to fix it.
> > > <img alt="image" width="947" src="https://user-images.githubusercontent.com/94120374/282027555-ca053f61-0e4a-4a5e-857b-711a6425611b.png">
> > 
> > 
> > cn account?
> 
> Yes, I found this type, the dictionary has no 'Purchase' value.
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/94120374/282036537-d07e3469-d277-4248-b756-1739bbf091f7.png">

Will fix it. Thanks

**Comment by yihong0618** [comment]
@imwsl which element do you print?

**Comment by imwsl** [comment]
> > > I met the same error, and I don't know how to fix it.
> > > <img alt="image" width="947" src="https://user-images.githubusercontent.com/94120374/282027555-ca053f61-0e4a-4a5e-857b-711a6425611b.png">
> > 
> > 
> > cn account?
> 
> Yes, I found this type, the dictionary has no 'Purchase' value.
> 
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/94120374/282036537-d07e3469-d277-4248-b756-1739bbf091f7.png">

I fixed this problem, but I changed some lines.

<img width="785" alt="image" src="https://github.com/yihong0618/Kindle_download_helper/assets/94120374/4452ec0e-aad8-4b3e-aac6-10b4ead8ebd9">

**Comment by yihong0618** [comment]
@imwsl nice job will make a commit now, and can you take a look if I had solved this?

**Comment by imwsl** [comment]
> @imwsl nice job will make a commit now, and can you take a look if I had solved this?

yeah, I will give some details about this problem later, it's Friday, I must get off work and go home immediately now. ^_^

**Comment by yihong0618** [comment]
@imwsl fixed it, please check and have a good weekend

**Comment by imwsl** [comment]
good job, I checked the no_kindle.py file, it seems fixed my problem. We modified the same parts😀

I will test this tonight later

**Comment by imwsl** [comment]
![image](https://github.com/yihong0618/Kindle_download_helper/assets/94120374/fdeb13a3-c3c6-4770-bfee-9394f50b2004)

Hi, I found a bug about the newest update. We need check the dictionary's return value, because sometimes it may return to a list and the program will crash.

sorry bro, it's too late to pull a request and my code is not good, I pasted picture above, you can check this problem by yourself. ^_^

PS. you did a great job , it helps me a lot... thanks.

**Comment by yihong0618** [comment]
@imwsl thanks will fix today

**Comment by yihong0618** [comment]
@imwsl try to fix, can you try the latest code?
Thanks a lot.

**Comment by imwsl** [comment]
> @imwsl try to fix, can you try the latest code?
> Thanks a lot.

Okay，I will try the latest code tonight. 😀

**Comment by imwsl** [comment]
![Screenshot_20231111-162051~2.png](https://github.com/yihong0618/Kindle_download_helper/assets/94120374/e1bab290-caf9-42e2-ad88-2d1804e6d7a5)

I checked the commit in my phone, I found something wrong. My problem is that origin return to a list not origins. So we shall check them both. 

I will try the least code, please wait for a while.

**Comment by yihong0618** [comment]
> ![Screenshot_20231111-162051~2.png](https://user-images.githubusercontent.com/94120374/282230497-e1bab290-caf9-42e2-ad88-2d1804e6d7a5.png)
> 
> I checked the commit in my phone, I found something wrong. My problem is that origin return to a list not origins. So we shall check them both.
> 
> I will try the least code, please wait for a while.

fixed the origin. thanks again

**Comment by imwsl** [comment]
> ![Screenshot_20231111-162051~2.png](https://user-images.githubusercontent.com/94120374/282230497-e1bab290-caf9-42e2-ad88-2d1804e6d7a5.png)
> 
> I checked the commit in my phone, I found something wrong. My problem is that origin return to a list not origins. So we shall check them both.
> 
> I will try the least code, please wait for a while.



Hi, I test the latest code, it works! 

![image](https://github.com/yihong0618/Kindle_download_helper/assets/94120374/4d35c6a1-6ad9-4790-aafa-525b41f973ec)

**Comment by yihong0618** [comment]
cool you can use `--memory` command to generate your memory
