### ISSUE TITLE
考虑更换mobi库为moki

### ISSUE THREAD

**Issue by bk1412** [yihong0618/Kindle_download_helper#152]
我移除了mobi库中的print警告信息 Warning: Bad key, size, value combination detected in EXTH  406 16 0000000000000000 
，此消息产生并非出现异常，主要是初版库作者的打印日志的坏习惯，mobi库移除了大部分print打印的日志，但是这条遗漏了。

moki是我移除消息后重新打包的库，只是移除了那条print,其他没有改动，包的依赖项目也都是和mobi中的依赖一样，经过测试是正常运行

**Comment by yihong0618** [comment]
可以给上游提个 pr?
我之前也想做你这个工作来的给忘了。。。

**Comment by bk1412** [comment]
> 可以给上游提个 pr? 我之前也想做你这个工作来的给忘了。。。

上游mobi库的issue回复率让我觉得提了也会无视

**Comment by yihong0618** [comment]
好，感谢我找时间确认下改下。
这几天事情比较多我还在外面，可能不会及时抱歉

**Comment by yihong0618** [comment]
换成 moki 了，谢谢

**Comment by lingr7** [comment]
我这边没有权限push，PR需要重新fork，替换mobi为moki，没有全部换成，会报错
![image](https://github.com/yihong0618/Kindle_download_helper/assets/37898999/c4adc0c9-cd57-4f3d-9fb0-7ec039f3b8c3)
这样就能pass了。
