### ISSUE TITLE
请问是否可能获取Clipping文件

### ISSUE THREAD

**Issue by cnberg** [yihong0618/Kindle_download_helper#153]
感谢作者，解决了我的大麻烦！
但 Kindle 实体已卖，书库里面几百本书不知道哪些做过笔记，一本本点开实在是崩溃

**Comment by yihong0618** [comment]
@cnberg 目前已经可以了。。。但是我留好了接口一直没做。

https://github.com/yihong0618/Kindle_download_helper/blob/main/kindle_download_helper/no_kindle.py#L273

你有兴趣可以接着这块弄，没有的话需要等等我有精力的。。。

**Comment by yihong0618** [comment]
如果做完了 PR welcome

我的设计是这样的
生成一个 Clipping 的 md

```
书名 b->

bookmark1
bookmark2

书名b ->
bookmark1
bookmark2
```

当然你有更好的设计也欢迎

**Comment by cnberg** [comment]
🐂🍺，我周末看下！

**Comment by yihong0618** [comment]
@cnberg 我们做也行，等我腾出空哈

**Comment by yihong0618** [comment]
这周会更新。

**Comment by yihong0618** [comment]
@cnberg 做完了
