### ISSUE TITLE
ERROR - 404 Client Error: Not Found for url: https://www.amazon.cn/error

### ISSUE THREAD

**Issue by afonw** [yihong0618/Kindle_download_helper#155]
Hi
才发现这个好东西
干净的win10最新的chrome
1.4.1可以从浏览器获取cookie和csrf，1.5不行
然后都是报标题的错 还提示Amazon bot detect.
另外，Apple silicon的Mac无法使用gui

**Comment by yihong0618** [comment]
hi 没有实体设备请用置顶的 no_kindle 模式

**Comment by afonw** [comment]
谢谢指点 还是不行 kindle.py和no_kindle.py都不行 和https://github.com/yihong0618/Kindle_download_helper/issues/138情况一样

**Comment by yihong0618** [comment]
@afonw no_kindle 模式，网页退出重写登陆一遍，然后再在设置里面有个安全，再登陆一遍

**Comment by afonw** [comment]
> @afonw no_kindle 模式，网页退出重写登陆一遍，然后再在设置里面有个安全，再登陆一遍

不是很理解 安全设置里做什么呢？2FA改为关？现在就是关的

**Comment by yihong0618** [comment]
> > @afonw no_kindle 模式，网页退出重写登陆一遍，然后再在设置里面有个安全，再登陆一遍
> 
> 不是很理解 安全设置里做什么呢？2FA改为关？现在就是关的

第二个，你dia点进去会让你重新登陆
![image](https://github.com/yihong0618/Kindle_download_helper/assets/15976103/555eaf7f-3ffa-41c6-a4b4-dc8294d5e1bd)

**Comment by afonw** [comment]
已经来不及了 Amazon关了web服务了 现在都要通过app了

**Comment by yihong0618** [comment]
@afonw 

想办法绕过去了。
1. 保证不能用梯子得是 cn 的网络
2. 如果弹这个错误（下图），你需要下载亚马逊那个海外购app(中国商店）在里面登陆，然后把密码改了。再登陆一遍。
3.  rm .tokens .device_id 之后再执行一遍
4. 有 kindle readme 方式依然可用
![telegram-cloud-photo-size-5-6199448154479377281-x](https://github.com/yihong0618/Kindle_download_helper/assets/15976103/a8a2efd5-f2a3-4d76-a10e-7a09eb1cc967)

**Comment by afonw** [comment]
感谢大佬的无私帮组 我最后还是就旧版PC client手动下载丢Calibre DeDRM解决了 再次感谢

**Comment by yihong0618** [comment]
不客气

**Comment by zumurud** [comment]
> 感谢大佬的无私帮组 我最后还是就旧版PC client手动下载丢Calibre DeDRM解决了 再次感谢

你好，以及作者好，很抱歉在作者的页面来请教这个问题，只是我实在找不到办法了，目前网页完全无法进入设备管理之类的界面，很多工具都用不了，请问最后你是如何解决的？

**Comment by yihong0618** [comment]
> > 感谢大佬的无私帮组 我最后还是就旧版PC client手动下载丢Calibre DeDRM解决了 再次感谢
> 
> 你好，以及作者好，很抱歉在作者的页面来请教这个问题，只是我实在找不到办法了，目前网页完全无法进入设备管理之类的界面，很多工具都用不了，请问最后你是如何解决的？

访问这个 https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/

**Comment by zumurud** [comment]
> > > 感谢大佬的无私帮组 我最后还是就旧版PC client手动下载丢Calibre DeDRM解决了 再次感谢
> > 
> > 
> > 你好，以及作者好，很抱歉在作者的页面来请教这个问题，只是我实在找不到办法了，目前网页完全无法进入设备管理之类的界面，很多工具都用不了，请问最后你是如何解决的？
> 
> 访问这个 https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/

哇真的可以！太太太感激了！！！总算能救了！

**Comment by jiahe224** [comment]
> 感谢大佬的无私帮组 我最后还是就旧版PC client手动下载丢Calibre DeDRM解决了 再次感谢

你是有kindle物理设备，连接设备到电脑后用 1.41 版客户端下的吗

**Comment by jiahe224** [comment]
> @afonw
> 
> 想办法绕过去了。
> 
> 1. 保证不能用梯子得是 cn 的网络
> 2. 如果弹这个错误（下图），你需要下载亚马逊那个海外购app(中国商店）在里面登陆，然后把密码改了。再登陆一遍。
> 3. rm .tokens .device_id 之后再执行一遍
> 4. 有 kindle readme 方式依然可用
>    ![telegram-cloud-photo-size-5-6199448154479377281-x](https://private-user-images.githubusercontent.com/15976103/302484879-a8a2efd5-f2a3-4d76-a10e-7a09eb1cc967.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzIwMzYsIm5iZiI6MTcxMDAzMTczNiwicGF0aCI6Ii8xNTk3NjEwMy8zMDI0ODQ4NzktYThhMmVmZDUtZjJhMy00ZDc2LWExMGUtN2EwOWViMWNjOTY3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAwNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMzZhMzlkNDNiNDg2MDQzZTdkMGNlNDI3ZDkzZjczODAxMDI5ZDE2OGIxNGM4YjdiOTJmOGM2Mzg2YWQ2YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DobDynCSkf6252URAXp-kAKcggbZAFNPWkhdM6gw2g)

改了密码还是不行，提示如下：
{"response": 
{
"challenge": 
{"challenge_reason": "MissingRequiredAuthenticationData", 
"uri": "https://www.amazon.cn/ap/challenge?arb=19a83645-d058-420b-9aef-7440aca78088", 
"required_authentication_method": "OTPCode", 
"challenge_context": "PT|1|zUzeFqmUNaDUIyt8/TvDnDOY0sjfhl0gh5NH5dGQ2/zFmnSJLQOIWfq3nBrPpCz7hi3UQ2DnLAM3bSJKtOnAyXrLVYdQKJs73W51SNsI+J4aGC7NquuJ7klLa7cwq1KsqXyxr03qzT9Np5OlMRSwWCurkNdpBUocMJrn9cw+W0mhNlHxfPdn0zx0am5urGVVvvUeX63EghaLn1QBuLYH3K5fU9Wc83KzVoxPvvzz9jiOnmqMkCFNXnGX0dxINYfY57UMQZ616iFsEKTx0d3WP/SPkmby1MPLT3KMs+xeQ+AsN5oJ1VgM2sPphzLoHbhUsyawgkkOC1q3TGjto1FN44ktb4ci4dov1/6RoVcU3+yngFzvCbah76qaWutYuiK87QFibBwffAKxeUL3"}
}, 
"request_id": "c798358381a54ce7bf282fa65ffd849a"
}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "C:\Users\wjh\Downloads\Kindle_download_helper-1.5\no_kindle.py", line 5, in <module>
    no_main()
  File "C:\Users\wjh\Downloads\Kindle_download_helper-1.5\kindle_download_helper\no_cli.py", line 101, in no_main
    nk.make_library()
  File "C:\Users\wjh\Downloads\Kindle_download_helper-1.5\kindle_download_helper\no_kindle.py", line 154, in make_library
    r = self.session.send(
  File "C:\Users\wjh\Downloads\Kindle_download_helper-1.5\kindle_download_helper\no_kindle.py", line 40, in new_send
    return old_send(*args, **kwargs)
  File "C:\Users\wjh\AppData\Local\miniconda3\lib\site-packages\requests\sessions.py", line 684, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
  File "C:\Users\wjh\AppData\Local\miniconda3\lib\site-packages\requests\utils.py", line 874, in resolve_proxies
    url = request.url
AttributeError: 'NoneType' object has no attribute 'url'

**Comment by jiahe224** [comment]
改密码后网页版没有地方登录了，https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/，这个也不行，以前是浏览器记住密码

**Comment by yihong0618** [comment]
> 改密码后网页版没有地方登录了，[https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/，这个也不行，以前是浏览器记住密码](https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/%EF%BC%8C%E8%BF%99%E4%B8%AA%E4%B9%9F%E4%B8%8D%E8%A1%8C%EF%BC%8C%E4%BB%A5%E5%89%8D%E6%98%AF%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%B0%E4%BD%8F%E5%AF%86%E7%A0%81)

手机重新登陆一次

**Comment by jiahe224** [comment]
> > 改密码后网页版没有地方登录了，[https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/，这个也不行，以前是浏览器记住密码](https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/%EF%BC%8C%E8%BF%99%E4%B8%AA%E4%B9%9F%E4%B8%8D%E8%A1%8C%EF%BC%8C%E4%BB%A5%E5%89%8D%E6%98%AF%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%B0%E4%BD%8F%E5%AF%86%E7%A0%81)
> 
> 手机重新登陆一次

手机和电脑都重新登录后还是不行，麻了，想不出是哪的问题

**Comment by dawnwind** [comment]
> > > 改密码后网页版没有地方登录了，[https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/，这个也不行，以前是浏览器记住密码](https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll/dateDsc/%EF%BC%8C%E8%BF%99%E4%B8%AA%E4%B9%9F%E4%B8%8D%E8%A1%8C%EF%BC%8C%E4%BB%A5%E5%89%8D%E6%98%AF%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%B0%E4%BD%8F%E5%AF%86%E7%A0%81)
> > 
> > 
> > 手机重新登陆一次
> 
> 手机和电脑都重新登录后还是不行，麻了，想不出是哪的问题

请问你最后解决了吗，怎么解决的
