### ISSUE TITLE
亚马逊首页Kindle入口消失后的访问自己已够书库的URL

### ISSUE THREAD

**Issue by lvscar** [yihong0618/Kindle_download_helper#156]
前几天发现amazon.cn首页已经找不到Kindle已购书库的访问入口， 通过客服电话联系后才得到一个能访问的URL：

[http://z.cn/hz/mycd/digital-console/contentlist](http://z.cn/hz/mycd/digital-console/contentlist)

**Comment by yihong0618** [comment]
README 里就有啊

**Comment by yihong0618** [comment]
@lvscar 我加在置顶里吧，看的方便
