### ISSUE TITLE
Download Failed: 'content-disposition'

### ISSUE THREAD

**Issue by a0x** [yihong0618/Kindle_download_helper#160]
Platform: Win 10 x86_64
Python: Python 3.11

尝试用GUI和`kindle.py`行执行下载，均可成功获取图书列表，但都遇到了相同的报错（如题，如图），每一本图书文件均以download failed告终，且报错内容均为 content-disposition，最终显示all done，但实际上没有下载任何书籍。
![image](https://github.com/yihong0618/Kindle_download_helper/assets/3829546/21383ce3-0d33-4071-9aa7-74e1226b31da)

_使用`no_kindle.py`能够成功下载。_

我本身也懂开发，所以想问一下，可能是哪里出现问题？这样我能够尽快调试出来~  感谢：）

**Comment by yihong0618** [comment]
可能下载已经失效了。。。我们看一下

**Comment by yihong0618** [comment]
@a0x 你目前有 kinde 实体设备么？

**Comment by a0x** [comment]
我没有Kindle实体设备，但是Windows、macOS、Android、iOS设备上都安装有Kindle的应用程序或App。

**Comment by yihong0618** [comment]
> 我没有Kindle实体设备，但是Windows、macOS、Android、iOS设备上都安装有Kindle的应用程序或App。

那不行，用下面的方式下载必须要有实体设备，如果没有实体设备只能用 no_kindle 下载
