### ISSUE TITLE
登陆美亚提示Failed to get CSRF token, please input怎么破？

### ISSUE THREAD

**Issue by puppet360** [yihong0618/Kindle_download_helper#161]
大佬们，登陆美亚一直提示Failed to get CSRF token, please input，怎么破，gui的1.4跟1.5版本都有这个问题。
![微信图片_20240308164414](https://github.com/yihong0618/Kindle_download_helper/assets/135691133/755472c5-9d1b-4e13-a3a4-99d81d91b8df)

**Comment by yihong0618** [comment]
手动粘

**Comment by puppet360** [comment]
好吧，手动粘确实可以！
