### ISSUE TITLE
已购的书籍提示有更新，但更新报错，有人知道怎么解决吗

### ISSUE THREAD

**Issue by Plixs** [yihong0618/Kindle_download_helper#163]
谢谢
![wufagengxin1](https://github.com/yihong0618/Kindle_download_helper/assets/4444175/d78ca15e-2104-4d44-bd2d-e76cd0479a5f)
![wufagengxin2](https://github.com/yihong0618/Kindle_download_helper/assets/4444175/f06cb22d-f424-4f06-bb1b-6966d15e3090)
![wufagengxin3](https://github.com/yihong0618/Kindle_download_helper/assets/4444175/310e9d4e-0d2e-4252-bf68-0fb26302e675)

**Comment by yihong0618** [comment]
这个没办法/

**Comment by Plixs** [comment]
> 这个没办法/

用户又又又被商家踩在地上 :(

**Comment by yihong0618** [comment]
> > 这个没办法/
> 
> 用户又又又被商家踩在地上 :(

因为中国的商店都关了。

**Comment by Plixs** [comment]
close
