### ISSUE TITLE
是不是最新的网页上有机器人检查，这个脚本不能下载了？执行完发现DOWNLOAD里面没有书

### ISSUE THREAD

**Issue by huangzekai** [yihong0618/Kindle_download_helper#167]
Amazon bot check detected, sleep 3 sec
Using default device serial Number: G090G10575140CF7
All done books saved in `DOWNLOAD`, dedrm files saved in `DEDRMS`
the device serial number can also be found here: DOWNLOADS/key.txt

**Comment by Plixs** [comment]
现在不清楚，前两天我试过下载没问题，bot check detected, sleep 3 sec理论就是加了睡眠防被检测，具体代码实现我没看

**Comment by yihong0618** [comment]
> Amazon bot check detected, sleep 3 sec Using default device serial Number: G090G10575140CF7 All done books saved in `DOWNLOAD`, dedrm files saved in `DEDRMS` the device serial number can also be found here: DOWNLOADS/key.txt

DEDRM 和 EPUB 里也没有么？
