### ISSUE TITLE
报错sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 

### ISSUE THREAD

**Issue by mayan368** [yihong0618/Kindle_download_helper#20]
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 
![image](https://user-images.githubusercontent.com/24467503/172522253-0cb0e298-fec1-4629-a487-59394fe7d4d5.png)

**Comment by yihong0618** [comment]
试着用 README 中的 --cookie 试一下。这个应该是 browercookie 的问题。
