### ISSUE TITLE
输出的key填写到 eInk Kindle Books 里提示序列号只有16位

### ISSUE THREAD

**Issue by uoiszero** [yihong0618/Kindle_download_helper#22]
![alt=图片](https://user-images.githubusercontent.com/6318185/172532739-5f7ee761-0250-4ce8-a6d0-68558d833932.png)

或者说这个key不应该填在这里

**Comment by lingr7** [comment]
我遇到问题是32位。

**Comment by wolfg1969** [comment]
检查下亚马逊帐号里的默认设备是不是个 Kindle 设备。

我没有 Kindle 设备，按照此文下载安装了旧版的 Kindle App 并设置为默认设备，然后用脚本下载书籍。DeDRM 配置选择 "Kindle for Mac/PC ebooks" 添加 default_key 。导入 Calibre 后，所有 azw 文件都被转换为 mobi 格式。

**Comment by uoiszero** [comment]
> 检查下亚马逊帐号里的默认设备是不是个 Kindle 设备。
> 
> 我没有 Kindle 设备，按照[此文](https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/)下载安装了旧版的 Kindle App 并设置为默认设备，然后用脚本下载书籍。DeDRM 配置选择 "Kindle for Mac/PC ebooks" 添加 default_key 。导入 Calibre 后，所有 azw 文件都被转换为 mobi 格式。

已解决。
简单说就是按照上文链接中提供的地址下载旧版本app，然后在网站上设置好默认设备，再使用脚本下载，下载回的书籍后缀是azw，而不是之前的kfx或者azw3。

**Comment by KiligWYu** [comment]
我用本脚本下载下来的虽然是 azw 格式书籍，但是无法去除 DRM，经过尝试，最后的解决方案是用 [1.31 版本的 Kindle for Mac](https://s3.amazonaws.com/kindleformac/60175/KindleForMac-1.31.60175.dmg) 下载书籍，用 [noDRM/DeDRM_tools](https://github.com/noDRM/DeDRM_tools) 去除 DRM。

**Comment by yihong0618** [comment]
@uoiszero 这个 issue 开着先？我觉得其他人也会遇到这个问题。

**Comment by lingr7** [comment]
windows下，使用Kindle for pc 1.17版本下载书籍，然后用 https://github.com/noDRM/DeDRM_tools去除DRM

**Comment by scegg** [comment]
> windows下，使用Kindle for pc 1.17版本下载书籍，然后用 https://github.com/noDRM/DeDRM_tools 去除DRM 作为安装到calibre，然后把文件拖到calibra窗口导入书籍，就自动去除DRM了。

DeDRM需要做什么配置吗。
插件安装后，重启Calibre，电子书拖进去，能显示出封面，但打开时候提示书有DRM保护。

**Comment by shuqian** [comment]
这个key到底怎么用呀

**Comment by yihong0618** [comment]
> 此文

https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/

**Comment by chongiscool** [comment]
搞了我小半天，终于还是站在大佬们的肩膀上，弄明白了怎么回事，请允许我捅破它。

> 我来定个性：可能跟 **序列号** 没什么关系。

我的背景：Kindle Paperwhite2，MacOS Catalina

大佬们多次提到的[此文](https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/)，能给我们几个消息【 下面，我以 macOS 的视角说，Windows的操作也类似 】
1. 如果正在使用 Surge 或 Clash 可使用规则屏蔽掉，否则忽略；
```
DOMAIN,kindleformac.s3.amazonaws.com,REJECT
DOMAIN,kindleforpc.s3.amazonaws.com,REJECT
```
2. 打开hosts文件`sudo vim  /private/etc/hosts`，将`127.0.0.1   kindleformac.s3.amazonaws.com`追加到hosts文件末尾；
3. 安装老版本的 Kindle for [Mac](https://s3.amazonaws.com/kindleformac/60175/KindleForMac-1.31.60175.dmg)/PC；
   1. 打开 Kindle，`cmd + ,`打开Kindle 偏好设置，取消「自动更新」；
   2. 可以忽略，设置 Kindle 首选项的 「内容文件夹」，因为我们用大佬的[项目](https://github.com/yihong0618/Kindle_download_helper)，跑脚本下载 *.aws；
   3. 禁用 KFX/KCR(即取消这个服务的运行权限) `chmod -x /Applications/Kindle.app/Contents/MacOS/renderer-test`
   4. 登录账号 Kindle for mac
4. 如果有Kindle硬件设备，注销登录先 【 Why？下面注意点第3点 】；在亚马逊Web网页[所有设备](https://www.amazon.cn/hz/mycd/digital-console/alldevices)上，设置你的mac上的设备为 `设为默认设备`，发送 1 本书试试看，到Kindle for mac 刷新下看看是否在下载；
   1. 网页上，退出登录，重新登录，check 亚马逊Web网页[所有设备](https://www.amazon.cn/hz/mycd/digital-console/alldevices)上 的 **默认设备** 是刚刚登录的 Kindle for mac
5. 此时，用大佬的[项目](https://github.com/yihong0618/Kindle_download_helper)，跑脚本下载的书，应该是 `your_local_path/Kindle_download_helper/DOWNLOADS/*.azw` 格式
6. 下载 [DeDRM_tools](https://github.com/noDRM/DeDRM_tools/releases/download/v10.0.3/DeDRM_tools_10.0.3.zip)，mac下双击解压后，关注点在 `DeDRM_plugin.zip`这个文件上，后续 Calibre 要用它；
7. 下载 [Calibre for macOS](https://calibre-ebook.com/download_osx), `cmd + f`搜索 `Catalina`，找到第3点；下载和安装，打开时，貌似要你注册或登录，退出重新打开，就OK了。
   1. 添加插件：`cmd + ,` -> 插件(Plugins) -> 从文件中载入插件（Load plugin from file） -> 上面第6点的`DeDRM_plugin.zip`，-> 打开(Open)；退出 Calibre，再打开它；
   2. 将 `your_local_path/Kindle_download_helper/DOWNLOADS/key.txt` 文件移动到其它地方，使 `your_local_path/Kindle_download_helper/DOWNLOADS/` 目录下全是 .azw的电子书
   3. Calibre 菜单栏上的「添加书籍」右侧 ▼ 按钮中选择「从单一文件夹添加所有书籍(Add books from single folder)」，选择 `your_local_path/Kindle_download_helper/DOWNLOADS` 文件夹，随着书籍的添加，你在Calibre中看到的书籍，都被转化成 .mobi 了；
   4. **全选**书籍，右键保存到磁盘(save to disk) -> 保存到单一文件夹(save to disk in a single folder) -> 选择一个保存的目录`~/Download/Kindle_books_mobi`；你快要成功了。
   5. 清理：在`~/Download/Kindle_books_mobi`文件夹内有「杂质」，`rm -rf ~/Downloads/Kindle_books_mobi/*.jpg` 和 `rm -rf ~/Downloads/Kindle_books_mobi/*.opf`。你成功了！


注意
1. 我在设置 Kindle for mac为`设为默认设备`情况下，关闭 Kindle Paperwhite2 的wifi，都还能下载成 .azw3 的电子书，于是索性注销（退出登录）它，才能下载 .azw 文件；
2. 我们被 「 序列号 」或者 [此文](https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/) 的「网页下载的电子书需要序列号处理」小节内容，带节奏了。不需要这些步骤哈：）
3. 需要转换成 epub 格式，就能在 Apple Books中看，可参考[此文](https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/)「转换格式」小节；

最后，感谢大佬们的开源奉献，我也注入一丝丝力量 : )

**Comment by otakutyrant** [comment]
> 检查下亚马逊帐号里的默认设备是不是个 Kindle 设备。
> 
> 我没有 Kindle 设备，按照[此文](https://divineengine.net/article/how-to-remove-drm-from-kindle-books-with-calibre/)下载安装了旧版的 Kindle App 并设置为默认设备，然后用脚本下载书籍。DeDRM 配置选择 "Kindle for Mac/PC ebooks" 添加 default_key 。导入 Calibre 后，所有 azw 文件都被转换为 mobi 格式。

你说的 Kindle App，是 Kindle for Windows 吗？

**Comment by otakutyrant** [comment]
我没有 Kindle，所以我尝试 [uoiszero](https://github.com/uoiszero) 的办法安装 Kindle for Windows 并设为默认设备，还是不行。此外我在 amazon.cn 尝试过「通过电脑下载USB传输」，官方报错：「您没有为此内容注册任何兼容的设备。」成功的用户就能正常地「通过电脑下载USB传输」吗？

**Comment by otakutyrant** [comment]
最后还是通过 Kindle for Windows 点一遍书籍以下载，接着在 Calibre 选择文件夹导入全部了……所以书不是特别多的话就没必要折腾这脚本了。

**Comment by yihong0618** [comment]
目前不用折腾，一条命令就可以了

**Comment by plutomiao** [comment]
> 我用本脚本下载下来的虽然是 azw 格式书籍，但是无法去除 DRM，经过尝试，最后的解决方案是用 [1.31 版本的 Kindle for Mac](https://s3.amazonaws.com/kindleformac/60175/KindleForMac-1.31.60175.dmg) 下载书籍，用 [noDRM/DeDRM_tools](https://github.com/noDRM/DeDRM_tools) 去除 DRM。

mac操作确实不需要序列号
