### ISSUE TITLE
download_one_book 异常 log 可以添加更多信息

### ISSUE THREAD

**Issue by louieh** [yihong0618/Kindle_download_helper#29]
https://github.com/yihong0618/Kindle_download_helper/blob/c9815fc398d53a0d59398aea260352cb47b5d12d/kindle.py#L208
* 在获取所有图书 ASIN 号的时候可以再拿下其它信息，比如 title。
这样下面循环执行 `download_one_book` 异常的时候可以打印图书标题，因为现在 log 里只有 ASIN，报错的时候会很好奇是哪本书。
* 所以我们是不是可以把过程中出错的图书信息暂存然后加个重试，或者把出错图书信息存成一个文件。
* 所以我们是不是可以再加个方法，传参 ASINs，来下载指定图书。

**Comment by frostming** [comment]
GUI 其实就是这么做的，先获取列表，再下载，下载成功的会标绿，没有标绿的可以下次再次点击下载，其中标绿的不会再重复下载

**Comment by louieh** [comment]
> GUI 其实就是这么做的，先获取列表，再下载，下载成功的会标绿，没有标绿的可以下次再次点击下载，其中标绿的不会再重复下载
哦哦好的，还没看 GUI 的代码。
