### ISSUE TITLE
KeyError: 'OwnershipData'、UnicodeDecodeError报错

### ISSUE THREAD

**Issue by WenCCWu** [yihong0618/Kindle_download_helper#31]
![image](https://user-images.githubusercontent.com/58162171/172885156-3227f92b-7264-4999-b840-7108742c0847.png)

**Comment by lostanother** [comment]
我也遇到这个问题，应该要手动输入cookie。作者那个找ajax的方法我不懂，用google到的[这篇博文](https://blog.csdn.net/whatday/article/details/107098251?depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-2-107098251-blog-54620402.pc_relevant_antiscanv4)中第二个方法看到了

**Comment by SuperQoo** [comment]
@lostanother 
请问是要把cookie 后面跟着的那一整段东西都复制到到 软件里去吗？
我复制进去了没有反应

**Comment by lostanother** [comment]
> 

右键点击cookie那栏会有”复制值“的选项，复制后就直接粘贴到软件里就行了

**Comment by lostanother** [comment]
> @lostanother 请问是要把cookie 后面跟着的那一整段东西都复制到到 软件里去吗？ 我复制进去了没有反应

@SuperQoo 右键点击cookie那栏会有”复制值“的选项，复制后就直接粘贴到软件里应该就可以了

**Comment by WenCCWu** [comment]
![捕获](https://user-images.githubusercontent.com/58162171/173086729-817fbd49-31b2-43cf-9a4c-bd30eab84a64.PNG)
手动获取cookie后确实可以下载了。
