### ISSUE TITLE
KeyError: 'OwnershipData' in win10

### ISSUE THREAD

**Issue by yandew** [yihong0618/Kindle_download_helper#33]
![Snipaste_2022-06-10_09-44-10](https://user-images.githubusercontent.com/58014565/172975229-db9bd8b1-ed62-4417-9769-f082ed4153e5.png)

**Comment by yandew** [comment]
win 10 without administrator, and use edge.

**Comment by yihong0618** [comment]
Do you have one kindle device?

**Comment by yandew** [comment]
Yes, I have a kindle.

**Comment by yihong0618** [comment]
Can you try it in terminal~? 
Maybe it is a bug.

**Comment by yandew** [comment]
How to run it in terminal?
Could you share the detail steps?
thanks.

**Comment by yihong0618** [comment]
@yandew 
1. login amazon.com
2. visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll/dateDsc/
3. right click this page source then find csrfToken value copy
4. run: python3 kindle.py ${csrfToken}
4. if is doc file python3 kindle.py ${csrfToken} --pdoc

**Comment by yandew** [comment]
1) I'm using a WIN10 system, And I have not python in it.
2) I have a Centos8 VM which is created via virtualbox
3) which python3 your x86 bin file need? python 3.9?
I get some error when I run it.
![image](https://user-images.githubusercontent.com/58014565/173006437-7859038e-d666-484f-8688-c4b6b64a8c18.png)

**Comment by frostming** [comment]
The error shows due to Authentication failed, please check:

1. CSRF token is correct, note the leading the ending whitespaces.
2. Try refreshing the page to get a new token
3. Manually input the cookie
4. Make sure the server you choose matches the site where you get the token and cookie.

**Comment by yandew** [comment]
thanks.
step3, how to manually input the cookie. I guess it's cookie isue.

**Comment by frostming** [comment]
@yandew Do you read Chinese after all? It is in the [README](https://github.com/yihong0618/Kindle_download_helper#%E6%89%8B%E5%8A%A8%E8%BE%93%E5%85%A5-cookie)

**Comment by yandew** [comment]
hi, it's solved after I input the cokkies manually.
the RCA is that I'm not the administrator usr of this laptop. the software can't be run as admin and can't get the cokkies from EDGE.
