### ISSUE TITLE
写了个dummy版

### ISSUE THREAD

**Issue by wanghaisheng** [yihong0618/Kindle_download_helper#41]
给那些不怎么懂编程  不想本地配环境的宝宝
点点点是白嫖的真谛
我的github action limit没了 没有测试

https://github.com/wanghaisheng/Kindle_download_helper_for_codedummy

**Comment by yihong0618** [comment]
感谢，我找时间试一下。

**Comment by wanghaisheng** [comment]
思路可行 我可以测一下 pr一个

**Comment by yihong0618** [comment]
我觉得另起一个 repo 作为你的，然后 README 里推荐好一些。

**Comment by wanghaisheng** [comment]
私有库就好其实  尊重你的建议
