### ISSUE TITLE
运行脚本下载的文件不带格式后缀

### ISSUE THREAD

**Issue by tsunhua** [yihong0618/Kindle_download_helper#47]
### 操作
本人使用 mac 使用运行 main分支（commit：5aea79681eec5b0d2073eb6064e33a8f9018bf15）上的代码，命令如下：

` ` ` 
python3 kindle.py --cn --pdoc
` ` ` 

### 结果

```
(19/23)downloading 鱼羊野史.第1-6卷 2094912 bytes
鱼羊野史.第1-6卷 downloaded
```

下载的文件没有后缀名，实际在 DOWNLOADS 目录中也是没有格式后缀。

### 期望
显示后缀名，因为我的文件有的是mobi格式的，有的是 azw 格式的，希望能区分开。

**Comment by yihong0618** [comment]
这个可能是已知问题 https://github.com/yihong0618/Kindle_download_helper/pull/18 
可能是 size 太大导致的。
正常下载 pdoc 会都是 awz3.

btw.
如果有方式解决这个问题 `PR` welcome

**Comment by tsunhua** [comment]
> 

已经提交 PR #48 ，请 Review

**Comment by NightFog007** [comment]
我mac通过命令下载的100多本书都没有后缀,有些很小的书也没有...

**Comment by tsunhua** [comment]
可以自行运行以下脚本，批量添加后缀名，更简单。

```python
import glob
import os


def rename():
    for file in glob.glob('DOWNLOADS/*'):
        if not file.endswith("txt"):
            os.rename(file, file + ".azw3")


if __name__ == '__main__':
    rename()
```

**Comment by yihong0618** [comment]
> 我mac通过命令下载的100多本书都没有后缀,有些很小的书也没有...

不知道你本地环境测试通过了没，我这边没有书来测试。

通过指，加上后缀，解密，阅读没有问题。

**Comment by frostming** [comment]
Oops, 应该是我的某一个提交搞坏了，修复ing
