### ISSUE TITLE
书名中有“/”字符导致下载失败

### ISSUE THREAD

**Issue by atempcode1** [yihong0618/Kindle_download_helper#53]
(56/65)downloading 此去经年 谁许我一纸繁华/胡适作品集 (民国大师经典书系) 463404 bytes
[Errno 2] No such file or directory: 'DOWNLOADS\\此去经年 谁许我一纸繁华/胡适作品集 (民国大师经典书系)'
此去经年 谁许我一纸繁华/胡适作品集 (民国大师经典书系) download failed

**Comment by atempcode1** [comment]
未测试的可能的fix：
diff --git a/kindle.py b/kindle.py  
index dc817a8..c4269e3 100644       
--- a/kindle.py
+++ b/kindle.py
@@ -10,6 +10,7 @@ import logging    
 import os
 import re
 from http.cookies import SimpleCookie
+from pathvalidate import sanitize_filename

 import browser_cookie3
 import requests
@@ -190,7 +191,7 @@ class Kindle:
             items = result["OwnershipData"]["items"]
             if filetype == "PDOC":
                 for item in items:
-                    item["title"] = html.unescape(item["title"])
+                    item["title"] = sanitize_filename(html.unescape(item["title"]))
                     item["authors"] = html.unescape(item.pop("author", ""))

             books.extend(items)
diff --git a/requirements.txt b/requirements.txt
index 5df0bfb..a2640fa 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,3 +1,4 @@
 requests
 browser-cookie3
 pywin32 ; sys_platform == 'win32'
+pathvalidate

**Comment by frostming** [comment]
GUI or CLI?

**Comment by atempcode1** [comment]
CLI

**Comment by frostming** [comment]
https://github.com/yihong0618/Kindle_download_helper/blob/527a3379436490fd3ef56c834ba3091e9aede3c6/kindle.py#L227

最新main分支上已经修复文件名，可以看到，/字符已经换成了_
