### ISSUE TITLE
Exception: Error: AUTHENTICATION_ERROR ?

### ISSUE THREAD

**Issue by xiaoliwe** [yihong0618/Kindle_download_helper#6]
Service：中亚. 
Device： MBP.
Browser：firefox version -101.0 (64 bit)
Steps：
`python3 kindle.py 'session-id=457-2081660-677xxxxxx' 'gs3EEtcTbLQNEHwxZmQZwbv8UBNarnOxNAAAAAQAAAABindUEP4nuL9RKfa6ow=='  --is-cn`

Response msg：  
`Traceback (most recent call last):
  File "/Users/xxxx/Desktop/Kindle_download_helper/kindle.py", line 227, in <module>
    kindle.download_books(start_index=options.index)
  File "/Users/xxx/Desktop/Kindle_download_helper/kindle.py", line 169, in download_books
    device = self.get_devices()[0]
  File "/Users/xxxx/Desktop/Kindle_download_helper/kindle.py", line 87, in get_devices
    raise Exception(
Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.cn/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie `

刷新firefox 后，重试，问题依旧 ；

**Comment by frostming** [comment]
能否测试下 #9 的代码，看看firefox是否工作正常？需要安装下依赖

**Comment by huabin** [comment]
@xiaoliwe 换 chrome 浏览器获取 cookie，firefox 获取的 cookie 包含了 `i18n` 的内容，会导致授权失败。

**Comment by huabin** [comment]
@xiaoliwe 换 chrome 浏览器获取 cookie，firefox 获取的 cookie 包含了 `i18n` 的内容，会导致授权失败。

**Comment by crystoneme** [comment]
跟楼主类似的错误信息，环境类似，我使用的是chrome

**Comment by xiaoliwe** [comment]
> 

working fine now and install the dependency package: `browsercookie`
<img width="391" alt="Screen Shot 2022-06-07 at 08 17 48" src="https://user-images.githubusercontent.com/9930176/172270472-6f588e37-22b7-45b9-b166-72580550b85e.png">

Thanks buddy ~

**Comment by xiaoliwe** [comment]
> 
Updating the latest code should be working fine, but I'm not re-testing it under the firefox browser. 
Anyway , Thanks again~

**Comment by xiaoliwe** [comment]
This problem has been solved and closed. 
Thx to all;

**Comment by texhy** [comment]
Hello everyone!
Please can anyone tell me how can I get the cookie from the amazon website. I tried getting it from networks panel in developer mode. Now what I dont understand is that, do we have to input all of the cookie as it is given there?
