### ISSUE TITLE
line 229, in get_all_books KeyError: 'items'

### ISSUE THREAD

**Issue by zzhanghub** [yihong0618/Kindle_download_helper#61]
测试了Win和MacOS平台，以及两个release版本，均出现该问题

```
Traceback (most recent call last):
File "kindle_download_helper.py", line 163, in on_fetch_books
File "kindle.py", line 229, in get_all_books
KeyError: 'items'
```
设备已经绑定，中亚
<img width="452" alt="iShot_2022-06-15_11 00 42" src="https://user-images.githubusercontent.com/25194962/173727607-ef603887-d62b-4296-9d8a-5c150b2a63de.png">

开发者如果有时间的话，麻烦看一下哦～

**Comment by scegg** [comment]
+1，我这里也是一样的问题呢。

直接执行release里的exe，报错是：
KeyError: 'items'

**Comment by frostming** [comment]
请测试下 0.4.2 的release

**Comment by frostming** [comment]
Duplicate with #56
