### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by hakumai7** [yihong0618/Kindle_download_helper#64]
[]ERROR - 404 Client Error: Not Found for url: https://www.amazon.co.jp/error
[]download failed

**Comment by yihong0618** [comment]
can you offer more info like screen shot or something else?

**Comment by hakumai7** [comment]
![image](https://user-images.githubusercontent.com/49392753/174427935-8e72d08f-c696-4eee-8068-086d3492e58b.png)


> can you offer more info like screen shot or something else?

![image](https://user-images.githubusercontent.com/49392753/174427943-2103d176-7abd-4569-aa1c-6ae018edc51d.png)

**Comment by yihong0618** [comment]
amazon jp seems can not download pdoc let me check
