### ISSUE TITLE
PDOC 目前无法下载

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/Kindle_download_helper#69]
Same as #54 

今天用的人太多触发了亚马逊的风控。

解决方式：
1. 更新到最新版，用 sleep 对抗风控
1. 等几天，亚马逊去掉风控
2. 不去下载 pdoc 只下载电子书，用 --resume-index 几次就搞定了。

**Comment by yihong0618** [comment]
ebooks 可能需要多重试几次。

**Comment by bladewang** [comment]
🤔 不知道大概有多少人被封了，另外封到的时候是什么症状呢？我今天又用的旧版本把自己的书下回来了几遍，四百本 ebook，一百多 pdoc 的样子。
