### ISSUE TITLE
命令行下载无法处理特殊空格和圆点

### ISSUE THREAD

**Issue by hnliuzesen** [yihong0618/Kindle_download_helper#73]
书名中带特殊空格（因为之前版本下载正常空格会作为文件名，这些不能处理的空格之前会被替换为_，与在亚马逊网站下载行为一致）和圆点（有一些正常有一些异常）的，下载下来会被截断，且大小为 0。
![image](https://user-images.githubusercontent.com/9082449/178949481-ac08c34f-6b6f-4a83-b079-4a8ce5688a74.png)
![image](https://user-images.githubusercontent.com/9082449/178949962-a0ed09db-cca6-4346-9f5c-bd1ff98db871.png)

**Comment by yihong0618** [comment]
我们看一下。

**Comment by yihong0618** [comment]
> 我们看一下。

@hnliuzesen 如果你有兴趣帮忙看一下这个 bug 欢迎哈/
