### ISSUE TITLE
Amazong Japan 遇到了问题，貌似无法下载

### ISSUE THREAD

**Issue by ding** [yihong0618/Kindle_download_helper#83]
执行时报如下错误：
```
Traceback (most recent call last):
  File "Kindle_download_helper/kindle.py", line 691, in <module>
    kindle.download_books(start_index=options.index - 1, filetype=options.filetype)
  File "Kindle_download_helper/kindle.py", line 513, in download_books
    device = self.get_devices()[0]
  File "Kindle_download_helper/kindle.py", line 251, in get_devices
    r = self.session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by yihong0618** [comment]
我们看看

**Comment by yihong0618** [comment]
这个错误看起来是网络连接的问题。

**Comment by ding** [comment]
我是在windows下取的cookie，然后在centos下run的，同样的方式对于amazon cn没问题，有点古怪。

**Comment by yihong0618** [comment]
wsl ?

**Comment by ding** [comment]
> wsl ?

不是，另外一台主机。wsl上我准备试试。

**Comment by yihong0618** [comment]
那可能不行。得是同一台

**Comment by ding** [comment]
换到mac上run了下，貌似读cookie有问题。

<img width="767" alt="image" src="https://user-images.githubusercontent.com/64532/181877057-45f69996-f2ee-4f2a-870e-601b6bb525fe.png">

**Comment by yihong0618** [comment]
奇怪，只有日亚？
主要我没有账号没法尝试。

**Comment by ding** [comment]
确实有点奇怪，中亚我是在windows下取的cookie和csrfToken，然后在别的centos主机上执行的命令，顺利下载了。为了下日亚的，我作了如下尝试，均失败。
- 换到同一台mac上操作
- 仅传入cookie
- 仅传入csrfToken
- 绑定一台实体kindle

若你不介意的话我提供你一个日亚帐号？

**Comment by yihong0618** [comment]
> 确实有点奇怪，中亚我是在windows下取的cookie和csrfToken，然后在别的centos主机上执行的命令，顺利下载了。为了下日亚的，我作了如下尝试，均失败。
> 
> * 换到同一台mac上操作
> * 仅传入cookie
> * 仅传入csrfToken
> * 绑定一台实体kindle
> 
> 若你不介意的话我提供你一个日亚帐号？

推上 dm 我试试？

**Comment by ding** [comment]
> > 确实有点奇怪，中亚我是在windows下取的cookie和csrfToken，然后在别的centos主机上执行的命令，顺利下载了。为了下日亚的，我作了如下尝试，均失败。
> > 
> > * 换到同一台mac上操作
> > * 仅传入cookie
> > * 仅传入csrfToken
> > * 绑定一台实体kindle
> > 
> > 若你不介意的话我提供你一个日亚帐号？
> 
> 推上 dm 我试试？

晚点哈，现在出门了。

**Comment by yihong0618** [comment]
@ding 我这边试了下可以。（我没有 jp 买书但有账号）报错是没设备

---

请问你加 '--jp' 参数了么？

**Comment by ding** [comment]
嗯，这个参数是肯定加了

**Comment by ding** [comment]
另外你的cookie和csrfToken都加了是么？csrfToken是从source中取的，还是request中取的？我两种应该都尝试过，依然是不行的。

**Comment by yihong0618** [comment]
都加了。都是在命令行中

**Comment by ding** [comment]
看下，这是我执行的命令行：
<img width="805" alt="image" src="https://user-images.githubusercontent.com/64532/181883131-f10fc11f-e8ca-4bff-b17f-f14bb58a0239.png">

**Comment by ding** [comment]
抱歉，python不熟，我大致加了一些log看了下，好像是cookie没能正确解析。
在下面的方法中
`def _parse_kindle_cookie(kindle_cookie)`

的 “cookie.load(kindle_cookie)” 后，看了下 “len(cookie.items())”，貌似是0.
难道日亚的cookie有什么特殊之处？

**Comment by yihong0618** [comment]
建议 chrome 试试

**Comment by ding** [comment]
> 

是使用的chrome取cookie和token的
Version 103.0.5060.114 (Official Build) (x86_64)

**Comment by ding** [comment]
Sorry, 是我的失误，cookie应该是没问题的，我参数用错了，应该是 `--cookie-file cookie.txt`，现在出现的问题好像是取不到设备
<img width="806" alt="image" src="https://user-images.githubusercontent.com/64532/181901174-1b6b963c-3abe-4d00-8714-0b5ca30689a5.png">

**Comment by ding** [comment]
但，我重新再执行了下，貌似已经开始下载了。。。。 这条issue我关了吧。。
