### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by LIVEINTHEOC** [yihong0618/Kindle_download_helper#90]
1.版本号标注在软件上。
2.软件使用说明的链接粘贴在软件上。
3.更新时候注明新增的新功能。
以上3点，希望有帮助，谢谢啦。

**Comment by frostming** [comment]
> 2.软件使用说明的链接粘贴在软件上。

使用说明就是Github地址，这个不用再加一个吧，其他的采纳
