### ISSUE TITLE
2个建议（之前邮件反应过，特意公开内容留言在这里）

### ISSUE THREAD

**Issue by LIVEINTHEOC** [yihong0618/Kindle_download_helper#92]
1.个人文档下载能否增加 比如 下载最近三个月、最近半年、最近一年的选项。因为之前版本没有类似选项，一旦开始下载，无法选择性停止。
2.软件能否显示下载所选文件所要占用的空间大小。

**Comment by yihong0618** [comment]
1. 的需求量比较小我感觉。倒是可以在命令行先添加
2. 是指整个的下载多大么？

**Comment by LIVEINTHEOC** [comment]
其实都是些可有可无的建议，现在的版本也足够用了。

**Comment by yihong0618** [comment]
> 其实都是些可有可无的建议，现在的版本也足够用了。

都可以有～，谢谢/

**Comment by yihong0618** [comment]
先关了哈
