### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by leo150** [yihong0618/Kindle_download_helper#93]
Having an error trying to download [this](https://www.amazon.com/gp/product/B07DJY4QVJ) book:
```
$ python3 kindle.py ${my_csrfToken}
Amazon open their bot check will sleep 3s
Using default device serial Number: ${my_serial}
404 Client Error: NotFound for url: https://www.amazon.com/gp/digital/common/error/cde-cannot-fulfill.html
Title: History of Chicago: A Captivating Guide to the People and Events that Shaped the Windy City’s History (U.S. States), Asin: B07DJY4QVJ download failed
```
Tried with `--pdoc` also no success. Any suggestions? Thanks.

**Comment by yihong0618** [comment]
only this book？

**Comment by yihong0618** [comment]
I will take a look about pdoc(^-^)

**Comment by leo150** [comment]
Thank you! That's the only book I have

**Comment by yihong0618** [comment]
@leo150 can you check if #94 can solve your problem or not?
sorry for late reply that I still have no amazon.com account yet.

**Comment by Tin** [comment]
@leo150 I see same thing on "specific book". It turns out the book is a illustrated book which is not suitable for my registered kindle devices (say kindle paper white). Please check if that's the case for you.

**Comment by leo150** [comment]
Yes it might be the case, I don't have any other books. Was looking for a way to download this specific book from my kindle store to read it in Apple Books but ended up downloading it from a different place.

**Comment by youniverse-zhao** [comment]
I'm using the code from the master branch with #94, but I'm still facing the same issue with all my books. 

Command used:
```shell
python3 kindle.py --cn --cut-length 80 ${my_csrf_token} --cookie-file ${my_cookie_file}
```

Sample output:
```log
Amazon open their bot check will sleep 3s
Using default device serial Number: ${my_serial_number}
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 魔鬼统计学（《经济学人》年度商业图书、史蒂芬·莱维特重磅推荐，匪夷所思的统计学脑洞，你以为不能算的其实可以算！）, Asin: B08NJBTPRC download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 新国标标点符号使用手册 (中华书局出品), Asin: B00Q2O72Z4 download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 野蛮进化：乔丹、科比御用极限训练师首度公开“统治者”潜能激发心理学 (科比布莱恩特亲笔作序！谷爱凌、虎扑网、网易体育倾情推荐！), Asin: B08YJ86LFY download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 论义务（西塞罗给儿子的长信，教子之道，媲美曾国藩家书） (译林人文精选), Asin: B0154K84CG download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 极简学习法【考试高分的秘密，上百位清北学霸学习方法大公开！郝景芳、刘嘉森、北大粽博士力荐！三步极简学习法，直击学习本质，有效刷题，科学抢分，从根上学，一通百通！每个家长都应该给孩子买的一本书 】, Asin: B09XMS385R download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 工作：巨变时代的现状、挑战与未来（曾经“劳动光荣”“勤劳致富”，如今它却只是让你我成了打工人。工作，它不顶用了，这是后工业化富足时代充满讽刺意味的背景！）, Asin: B09NLHDQ5F download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
```

**Comment by yihong0618** [comment]
did these books are kindle unlimited ？

**Comment by youniverse-zhao** [comment]
> did these books are kindle unlimited ？

No, they are all individual purchases.

**Comment by yihong0618** [comment]
do you have a kindle device or just kindle app?
I just tried mine and found no error.

**Comment by youniverse-zhao** [comment]
> do you have a kindle device or just kindle app? I just tried mine and found no error.

I only use Kindle apps and don't have a Kindle device. Maybe that's the issue.

**Comment by yihong0618** [comment]
@youniverse-zhao same as https://github.com/yihong0618/Kindle_download_helper/issues/95

**Comment by youniverse-zhao** [comment]
> @youniverse-zhao same as #95

Thanks! Will test tonight.

**Comment by wenbolwm** [comment]
![image](https://user-images.githubusercontent.com/1632932/192133596-92a12ee3-f3c2-436c-b95f-7d6d43e45e80.png)
![image](https://user-images.githubusercontent.com/1632932/192133641-f317defb-441f-4754-b0a3-47f798f6f4b1.png)
Amazon open their bot check will sleep 3s
Can't find device with serial number: A00108541XFKBH97L0TAF
Using default device serial Number: 5204641F921C4623B69800B401BDA84D
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 漫画算法：小灰的算法之旅（全网阅读量近1000万次的算法故事！！！一群可爱的小仓鼠，带你轻松入门算法与数据结构！） ( 博文视点图书), Asin: B07VWVLCXS download failed
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: Spring Boot实战 (图灵程序设计丛书), Asin: B0716WDRKV download failed

**Comment by chongiscool** [comment]
@wenbolwm，貌似你和[上面这位](https://github.com/yihong0618/Kindle_download_helper/issues/93#issuecomment-1253587276)遇到了同样的问题。应该是没有 Kindle 实体设备吧？你看完 #95 和 #22 后，大致能明白是个什么事，就能搞定了。它的整体思路：登录老版本 [Kindle for pc](https://s3.amazonaws.com/kindleforpc/51068/KindleForPC-installer-1.24.51068.exe)（用迅雷下载） ，亚马逊网页上设置其为默认设备，然后通过该项目下载书籍，再通过 [Calibre](https://calibre-ebook.com/download) 去掉 DRM。

**Comment by umonaca** [comment]
相同的问题，而且是突然出现的，之前还能用……

**Comment by yihong0618** [comment]
@umonaca 试了下能用，你是用 cli 跑的么？

**Comment by Falld0wn18** [comment]
> @wenbolwm，貌似你和[上面这位](https://github.com/yihong0618/Kindle_download_helper/issues/93#issuecomment-1253587276)遇到了同样的问题。应该是没有 Kindle 实体设备吧？你看完 #95 和 #22 后，大致能明白是个什么事，就能搞定了。它的整体思路：登录老版本 [Kindle for pc](https://s3.amazonaws.com/kindleforpc/51068/KindleForPC-installer-1.24.51068.exe)（用迅雷下载） ，亚马逊网页上设置其为默认设备，然后通过该项目下载书籍，再安装 [DeDRM tools](https://github.com/noDRM/DeDRM_tools) 插件到 [Calibre](https://calibre-ebook.com/download) 上，去掉书籍的 DRM。

测试过没有Kindle设备的情况下，将老版本Kindle设为默认设备，也无法用该项目下载书籍了，同样提示“404 Client Error“~

**Comment by yihong0618** [comment]
现在支持没有实体设备了
