### ISSUE TITLE
Client error 404 for amazon.cn

### ISSUE THREAD

**Issue by samuelye** [yihong0618/Kindle_download_helper#95]
可以列出书籍，但下载失败，报错：404 Client Error: Not Found for url: https://www.amazon.cn/error

下载是否必须要有Kindle物理设备？iOS的Kindle软件似乎无法在官网上用“通过下载USB传输”方式。

**Comment by yihong0618** [comment]
是的。

**Comment by yihong0618** [comment]
@samuelye 
可以尝试这个 issue 回复中的没设备怎么办。
https://github.com/yihong0618/Kindle_download_helper/issues/22

**Comment by samuelye** [comment]
@yihong0618 多谢!
