### ISSUE TITLE
批量unpack功能

### ISSUE THREAD

**Issue by zivilyyyn** [yihong0618/Kindle_download_helper#97]
能否在dedrm之后加入批量unpack成epub的功能，KOREADER识别不了azw3，calibre如果用unpack插件没法批量转换，自带的转换会带来奇怪的格式问题，并且文件名会变成全拼。

**Comment by yihong0618** [comment]
转换的话工作量比较大，我建议是你下个 epub 转换的软件然后写脚本搞定。

**Comment by zivilyyyn** [comment]
好的，感谢回复。

**Comment by yihong0618** [comment]
@zivilyyyn 我找个时间看看，能不能用第三方简单的直接 call 实现。

麻烦问一下你的操作系统是？

**Comment by zivilyyyn** [comment]
操作系统是win11 22h2

**Comment by yihong0618** [comment]
试试这个？
https://github.com/kevinhendricks/KindleUnpack

**Comment by zivilyyyn** [comment]
好的，我去看看，谢谢。
