### ISSUE TITLE
能否单独下载某一本书？

### ISSUE THREAD

**Issue by zenz** [yihong0618/Kindle_download_helper#98]
如题，貌似现在只能全部下载？
其中一本书下载失败，其他正常，然后要为这本下载失败的数重新下载所有书籍，如果再次失败……

**Comment by yihong0618** [comment]
@zenz 有些书是下不了的，因为亚马逊版权问题。

能提供下报错信息么？我记得逻辑是如果一本书下不了，会跳过，谢谢。

**Comment by zenz** [comment]
.error_books中记录的信息是
```
404 Client Error: Not Found for url: https://www.amazon.cn/error
404 Client Error: Not Found for url: https://www.amazon.cn/error
Title: 镖人9（轰动日本的中国漫画！漫画大师高桥留美子、藤泽亨，知名作家马伯庸，知名动画导演田晓鹏鼎力推荐！信念越强，力量越强）, Asin: B083BTVDYY download failed
Title: 镖人9（轰动日本的中国漫画！漫画大师高桥留美子、藤泽亨，知名作家马伯庸，知名动画导演田晓鹏鼎力推荐！信念越强，力量越强）, Asin: B083BTVDYY download failed
```
下载失败会跳过继续其他书籍的下载，但如何再次尝试单独下载这本下载失败的书籍呢？

**Comment by yihong0618** [comment]
这两本可能就是下不了。。。之前也有人遇到过类似的，你可以搜一下 issue

目前不提供这个功能。你可以尝试用 GUI GUI 会列出下载书的列表，可以单独下。

如果想单独下载某本书，你需要 print 出来这个书的号，然后改 kindle.py 里面的代码，在 list 里单独拿出这两本书下。

**Comment by zenz** [comment]
嗯，手动改了kindle_download_helper中的kindle.py，只下载指定的书籍，可以下载下来。
